In [2]:
print('创建一维的narray对象: \n',np.array([1,2,3,4,5]))
print('等价于: \n',np.arange(1,6))

print('linspace生成一个等差数列:',np.linspace(1,5,5))
print('logspace用于生成等比数列:',np.logspace(1,3,3)) # 在10^1 ～ 10^3之间生成3个数，组成等比数列
print('创建3*4的全1矩阵: \n',np.ones((3,4)))
print('创建3*4的全0矩阵: \n',np.zeros((3,4)))
print('创建3阶单位矩阵: \n', np.eye(3))
print('创建3*4的空矩阵: \n', np.empty((3,4)))

#In[1] np.from*?
print('获得字符串的ascii码序列fromstring: \n',np.fromstring('abcdef',dtype=np.int8))
print('获得字符串的ascii码序列frombuffer: \n',np.frombuffer(b"abcdef", dtype =  'i1')) #i1等价于np.int8

print('根据字符串生成矩阵S2: \n',np.frombuffer(b"abcdef", dtype =  'S2')) # S2表示2个字符，等价于a2
print('根据字符串生成矩阵a2: \n',np.frombuffer(b"abcdef", dtype =  'a2')) # S2表示2个字符，等价于a2

print('根据矩阵的行号列号生成矩阵: \n',np.fromfunction(lambda x,y:x+y,(3,4)))
print('复数矩阵：\n',np.mat([[2,3-2j],[4+2j,1]]))
#https://docs.scipy.org/doc/numpy/reference/generated/numpy.frombuffer.html

a = np.arange(4).reshape(1,4)
print("使用broadcast_to生产矩阵a=%s：\n"%a, np.broadcast_to(a,(4,4)))


import tempfile
fname = tempfile.mkstemp()[1]
A=np.eye(3)
A.tofile(fname)
print('save A to file: ',A,fname)
print('不建议使用：',np.fromfile(fname))

np.save(fname,A)
print('load ndarray: \n',np.load(fname + '.npy'))

print('根据iterator生成矩阵： ',np.fromiter(range(10),dtype=float))

创建一维的narray对象: 
 [1 2 3 4 5]
等价于: 
 [1 2 3 4 5]
linspace生成一个等差数列: [1. 2. 3. 4. 5.]
logspace用于生成等比数列: [  10.  100. 1000.]
创建3*4的全1矩阵: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
创建3*4的全0矩阵: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
创建3阶单位矩阵: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
创建3*4的空矩阵: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
获得字符串的ascii码序列fromstring: 
 [ 97  98  99 100 101 102]
获得字符串的ascii码序列frombuffer: 
 [ 97  98  99 100 101 102]
根据字符串生成矩阵S2: 
 [b'ab' b'cd' b'ef']
根据字符串生成矩阵a2: 
 [b'ab' b'cd' b'ef']
根据矩阵的行号列号生成矩阵: 
 [[0. 1. 2. 3.]
 [1. 2. 3. 4.]
 [2. 3. 4. 5.]]
复数矩阵：
 [[2.+0.j 3.-2.j]
 [4.+2.j 1.+0.j]]
使用broadcast_to生产矩阵a=[[0 1 2 3]]：
 [[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
save A to file:  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] /tmp/tmp4br4ih_w
不建议使用： [1. 0. 0. 0. 1. 0. 0. 0. 1.]
load ndarray: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
根据iterator生成矩阵：  [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [3]:
# 矩阵属性
a = np.array([1,2,3,4,5])
print('1维矩阵中元素个数：',a,a.shape)

b = np.array([[1,2,3,4,5],
              [6,7,8,9,10]])
print('矩阵形状(行数和列数): \n',b.shape)
print('2维矩阵中元素个数：',b.size)
print('维数: ',a.ndim,b.ndim)
print('flat属性：',[i for i in b.flat])

print('转换为列表： ',b.tolist())
print('转换为列表： ',list(b))
print('展平为1维ndarray： ',b.ravel(),type(b.ravel())) 
print('展平为1维ndarray： ',b.ravel(order="F")) # C:按行，F:按列, A:原顺序，k:元素在内存中的出现顺序
import scipy
print('NumPy和SciPy相互转化: ',scipy.asarray(a),)

# 矩阵切片
print('1. ',b[0:1],b[0:1].shape)     #2维矩阵，第一行
print('2. ',b[1,2:5],b[1,2:5].shape) #1维矩阵，第1行的2，3，4列

print('3. ',b[1,:],b[1,:].shape)     # 1维矩阵，第2行的所有列
print('4. ',b[b>3])                  # 1维矩阵，所有大于3的元素
print('5. 布尔索引： ',b>3)                     # 2维矩阵，True/False组成

a[a>3] = 0                     # 大于3的清零
print('6. ',a)
a = np.array([np.nan,  1,2,np.nan,3,4,5])  
print('7. 过滤nan：',a[~np.isnan(a)])

# 数据类型
#https://blog.csdn.net/zhili_wang/article/details/81140282
print('1. 数据类型',np.dtype('i4'),np.dtype('?'),np.dtype('f4'))
print('2. 长度为1的字符串：',np.dtype('a1'),np.dtype('S1'))


1维矩阵中元素个数： [1 2 3 4 5] (5,)
矩阵形状(行数和列数): 
 (2, 5)
2维矩阵中元素个数： 10
维数:  1 2
flat属性： [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
转换为列表：  [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
转换为列表：  [array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]
展平为1维ndarray：  [ 1  2  3  4  5  6  7  8  9 10] <class 'numpy.ndarray'>
展平为1维ndarray：  [ 1  6  2  7  3  8  4  9  5 10]
NumPy和SciPy相互转化:  [1 2 3 4 5]
1.  [[1 2 3 4 5]] (1, 5)
2.  [ 8  9 10] (3,)
3.  [ 6  7  8  9 10] (5,)
4.  [ 4  5  6  7  8  9 10]
5. 布尔索引：  [[False False False  True  True]
 [ True  True  True  True  True]]
6.  [1 2 3 0 0]
7. 过滤nan： [1. 2. 3. 4. 5.]
1. 数据类型 int32 bool float32
2. 长度为1的字符串： |S1 |S1


In [4]:
a1 = np.array([[4,5,6],[1,2,3]])
a2 = np.array([[6,5,4],[3,2,1]])

print('相加: \n',       a1+a2)
print('相除取商: \n',    a1/a2)
print('整数相除取商: \n', a1//a2)
print('相除取余数: \n',   a1%a2)

# 矩阵乘法必须满足矩阵乘法的条件，即第一个矩阵的列数等于第二个矩阵的行数。
# 叉乘，内积
a = np.array([[1,2,3],
               [4,5,6]]) # a1为2*3矩阵
b = np.array([[1,2],
               [3,4],
               [5,6]]) # a2为3*2矩阵

print(a.shape[1]==b.shape[0]) # True, 满足矩阵乘法条件
print(a.dot(b))               # 1*1+2*3+3*5  1*2+2*4+3*6
                              # 4*1+5*3+6*5  4*2+5*4+6*6
print('等价于： ',np.dot(a,b))


相加: 
 [[10 10 10]
 [ 4  4  4]]
相除取商: 
 [[0.66666667 1.         1.5       ]
 [0.33333333 1.         3.        ]]
整数相除取商: 
 [[0 1 1]
 [0 1 3]]
相除取余数: 
 [[4 0 2]
 [1 0 0]]
True
[[22 28]
 [49 64]]
等价于：  [[22 28]
 [49 64]]


In [5]:
# 转置
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
print(a.transpose())
print(a.T)

#改变形状
print("4行3列的新数组,a不变:",a.reshape(4,3))
a.resize(4,3)
print("4行3列的新数组:",a)

print('纵向拆分成2个矩阵：',np.array_split(a,2, axis=0))

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
4行3列的新数组,a不变: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
4行3列的新数组: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
纵向拆分成2个矩阵： [array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]


In [6]:
#统计函数
a = np.array([[1,2,3],
              [4,5,6]])
print('最大值: ',a.max()) 
print('最小值: ',a.min()) 
print('每一列最大值（以下函数均支持axis参数）: ',a.max(axis=0))
print('每一行最大值（以下函数均支持axis参数）: ',a.max(axis=1))

print('均值:',a.mean())
print('方差: ',a.var()) # 结果 2.91666666667
print('标准差： ',a.std())
print('中值: ',np.median(a))
print('求和: ',a.sum())
print('累积和: ',a.cumsum())
print('最大值-最小值：',np.ptp(a),np.ptp(a,axis=0),np.ptp(a,axis=1))
print('百分位数',np.percentile(a,40),np.percentile(a,50),np.percentile(a,60))

a = np.array([1,2,3,4]) 
wts = np.array([4,3,2,1]) 
print('加权平均值：',np.average(a,weights = wts )) # (1*4+2*3+3*2+4*1)/(4+3+2+1)

最大值:  6
最小值:  1
每一列最大值（以下函数均支持axis参数）:  [4 5 6]
每一行最大值（以下函数均支持axis参数）:  [3 6]
均值: 3.5
方差:  2.9166666666666665
标准差：  1.707825127659933
中值:  3.5
求和:  21
累积和:  [ 1  3  6 10 15 21]
最大值-最小值： 5 [3 3 3] [2 2]
百分位数 3.0 3.5 4.0
加权平均值： 2.0


In [7]:
# 矩阵遍历
a = np.arange(0,20,5) 
print('1维矩阵：%s\n迭代1：'%a)
for x in np.nditer(a):  
    print(x,end=' ')
print('\n迭代2：')
for x in a:             # 与上面相同
    print(x,end=' ')
a = np.array([[1,2,3],[4,5,6]]) 
print('\n2维矩阵：%s \n迭代1:' % a)
for x in np.nditer(a):  
    print(x,end=' ')
print('\n迭代2：')
for x in a:            # 与上面不同
    print(x,end=' ')

1维矩阵：[ 0  5 10 15]
迭代1：
0 5 10 15 
迭代2：
0 5 10 15 
2维矩阵：[[1 2 3]
 [4 5 6]] 
迭代1:
1 2 3 4 5 6 
迭代2：
[1 2 3] [4 5 6] 

In [8]:
a = np.arange(0,30,5) 
b = a.reshape(3,2)  
 
print("矩阵：\n",b)
print('以C风格顺序排序：' )      # C:按行，F:按列, A:原顺序，k:元素在内存中的出现顺序
for x in np.nditer(b, order =  'C'):  
    print(x,end='  ')

print('\n以F风格顺序排序：')
for x in np.nditer(b, order =  'F'):  
    print(x,end='  ')


矩阵：
 [[ 0  5]
 [10 15]
 [20 25]]
以C风格顺序排序：
0  5  10  15  20  25  
以F风格顺序排序：
0  10  20  5  15  25  

In [9]:
#swapaxes 交换数组的两个轴
a=np.arange(8).reshape(2,2,2)
b=np.swapaxes(a, 2, 0)

print(a,b,sep='\n---\n')

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
---
[[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]


In [10]:
# broadcasting机制
x = np.arange(4)
xx = x.reshape(4,1)
y = np.ones(5)
z = np.ones((3,4))
print("%s + %s = \n%s"% (xx,y,xx + y))
print("-----")
print("%s + \n %s = \n %s\n----" % (x,z,x + z))

a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
print("a=%s  b=%s \n" % (a,b),a[:, np.newaxis] + b)

[[0]
 [1]
 [2]
 [3]] + [1. 1. 1. 1. 1.] = 
[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]
-----
[0 1 2 3] + 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] = 
 [[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]
----
a=[ 0. 10. 20. 30.]  b=[1. 2. 3.] 
 [[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [11]:
#模拟broadcasting机制
x = np.array([[1], [2], [3]]) 
y = np.array([4, 5, 6]) 
b = np.broadcast(x,y)  

print("b.shape=",b.shape)

# 手动使用 broadcast 将 x 与 y 相加
c = np.empty(b.shape) 
c.flat = [u + v for (u,v) in b] 
print("c=",c)

print("等价于：x + y=\n",x + y)

b.shape= (3, 3)
c= [[5. 6. 7.]
 [6. 7. 8.]
 [7. 8. 9.]]
等价于：x + y=
 [[5 6 7]
 [6 7 8]
 [7 8 9]]


In [12]:
#squeeze删除1维
x = np.arange(9).reshape(1,3,3)
a = np.squeeze(x)
print("before squeeze:\n%s\n after squeeze:\n%s"%(x,a))

before squeeze:
[[[0 1 2]
  [3 4 5]
  [6 7 8]]]
 after squeeze:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
# concatenate 矩阵合并
a1 = np.array([[1,2],
               [3,4]])
a2 = np.array([[5,6],
               [7,8]])

print('1. 水平合并hstack\n',np.hstack([a1,a2])) 
print("2. 水平合并concatenate：\n", np.concatenate((a1,a2), axis=1))

print('3. 垂直合并vstack\n',np.vstack([a1,a2])) 
print("4. 垂直合并concatenate：\n", np.concatenate((a1,a2), axis=0))

x=np.hstack([a1,a2])
print('水平分割%s：\n'%x,np.hsplit(x,2))

1. 水平合并hstack
 [[1 2 5 6]
 [3 4 7 8]]
2. 水平合并concatenate：
 [[1 2 5 6]
 [3 4 7 8]]
3. 垂直合并vstack
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
4. 垂直合并concatenate：
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
水平分割[[1 2 5 6]
 [3 4 7 8]]：
 [array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [14]:
#stack堆叠
a = np.array([[1,2],[3,4]]) 
b = np.array([[5,6],[7,8]]) 
c=np.stack((a,b),0)
print('沿轴0堆叠两个数组\na=\n%s\nb=\n%s\nc=\n%s\nc.shape=%s'%(a,b,c,c.shape))
c=np.stack((a,b),1)
print('沿轴0堆叠两个数组\na=\n%s\nb=\n%s\nc=\n%s\nc.shape=%s'%(a,b,c,c.shape))

沿轴0堆叠两个数组
a=
[[1 2]
 [3 4]]
b=
[[5 6]
 [7 8]]
c=
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
c.shape=(2, 2, 2)
沿轴0堆叠两个数组
a=
[[1 2]
 [3 4]]
b=
[[5 6]
 [7 8]]
c=
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
c.shape=(2, 2, 2)


In [15]:
# append
a = np.array([[1,2,3],
              [4,5,6]]) 
 
print('append：',np.append(a, [7,8,9]))
print('沿轴 0 添加元素：', np.append(a, [[7,8,9]],axis = 0))
print('沿轴 1 添加元素：',np.append(a, [[5,5,5],[7,8,9]],axis = 1))

append： [1 2 3 4 5 6 7 8 9]
沿轴 0 添加元素： [[1 2 3]
 [4 5 6]
 [7 8 9]]
沿轴 1 添加元素： [[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


In [16]:
#Insert
a = np.array([[1,2],[3,4],[5,6]]) 

print('未传递Axis参数，数组展开后在第3个元素后插入：',np.insert(a,3,[11,12]))
print('沿轴 0 广播：',np.insert(a,1,[11],axis = 0))
print('沿轴 1 广播：',np.insert(a,1,11,axis = 1))


未传递Axis参数，数组展开后在第3个元素后插入： [ 1  2  3 11 12  4  5  6]
沿轴 0 广播： [[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]
沿轴 1 广播： [[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


In [17]:
#delete
a = np.arange(12).reshape(3,4) 
 
print('第一个数组:\n',a)
print('未传递Axis参数,数组展开后删除第6项：' ,np.delete(a,5) )
print('删除第二列：\n' ,np.delete(a,1,axis = 1))

a = np.array([1,2,3,4,5,6,7,8,9,10]) 
print('包含从数组中删除的替代值的切片：', np.delete(a, np.s_[::2]))


第一个数组:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
未传递Axis参数,数组展开后删除第6项： [ 0  1  2  3  4  6  7  8  9 10 11]
删除第二列：
 [[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]
包含从数组中删除的替代值的切片： [ 2  4  6  8 10]


In [18]:
#unique
a = np.array([5,2,6,2,7,5,6,8,2,9]) 
 
print('去重：',a, np.unique(a))

u,indices = np.unique(a, return_index = True) 
print('去重数组所对应的索引：',u,indices )

u,indices = np.unique(a,return_inverse = True) 
print('去重元素的下标：',indices,all(u[indices]==a)) 

u,indices = np.unique(a,return_counts = True) 
print('去重元素的重复数量：',indices)

去重： [5 2 6 2 7 5 6 8 2 9] [2 5 6 7 8 9]
去重数组所对应的索引： [2 5 6 7 8 9] [1 0 2 4 7 9]
去重元素的下标： [1 0 2 0 3 1 2 4 0 5] True
去重元素的重复数量： [3 2 2 1 1 1]


In [19]:
#位运算
print('13 和 17 的二进制形式：', bin(13), bin(241),
                              np.binary_repr(13, width = 8),
                              np.binary_repr(242, width = 8)) 
print('与：', np.bitwise_and(13, 242))
print('或：', np.bitwise_or(13, 242))
print('反转:', np.invert(np.array([13], dtype = np.uint8)))



13 和 17 的二进制形式： 0b1101 0b11110001 00001101 11110010
与： 0
或： 255
反转: [242]


In [20]:
#位移
print("10和40的2进制：",np.binary_repr(10, width = 8), np.binary_repr(40, width = 8))
print('将 10 左移两位：',np.left_shift(10,2))
print('将 40 右移两位：', np.right_shift(40,2))

10和40的2进制： 00001010 00101000
将 10 左移两位： 40
将 40 右移两位： 10


In [21]:
#字符串处理，可以针对整个矩阵生效
print('连接两个字符串：\n', np.char.add(['hello'],[' xyz']),
                          np.char.add(['hello', 'hi'],[' abc', ' xyz']))
print('多重连接: ',np.char.multiply('Hello ',3))
print('center: ',np.char.center('hello', 20,fillchar = '*'))
print('capitalize: ',np.char.capitalize('hello world'))
print('title: ',np.char.title('hello how are you?'))
print('lower: ',np.char.lower(['HELLO','WORLD']))
print('upper: ',np.char.upper([['hello'],['world']]))
print('split: ',np.char.split ('TutorialsPoint,Hyderabad,Telangana', sep = ','))
print('splitlines: ',np.char.splitlines('hello\nhow are you?') )
print('join: ', np.char.join(':','dmy'), np.char.join([':','-'],['dmy','ymd']))
print('replace: ',np.char.replace ('He is a good boy', 'is', 'was'))

a = np.char.encode('hello', 'cp500') 
print("encode and decode:",a,np.char.decode(a,'cp500'))

连接两个字符串：
 ['hello xyz'] ['hello abc' 'hi xyz']
多重连接:  Hello Hello Hello 
center:  *******hello********
capitalize:  Hello world
title:  Hello How Are You?
lower:  ['hello' 'world']
upper:  [['HELLO']
 ['WORLD']]
split:  ['TutorialsPoint', 'Hyderabad', 'Telangana']
splitlines:  ['hello', 'how are you?']
join:  d:m:y ['d:m:y' 'y-m-d']
replace:  He was a good boy
encode and decode: b'\x88\x85\x93\x93\x96' hello


In [22]:
a=np.array([[11,1,2],[12,8,9]])
print('最大值所在位置的索引：',a.argmax())
print('每一行最大值所在位置的索引：',a.argmax(axis=1))
print('每一行最小值所在位置的索引：',a.argmin(axis=1))
print('索引为1的最小，索引为0的最大: \n',a.argsort())

print('对矩阵a中每个元素取正弦: ',np.sin(a))	
print('对矩阵a中每个元素取余弦: ',np.cos(a))	
print('对矩阵a中每个元素取正切: ',np.tan(a))
print('对矩阵a中每个元素取反正弦: ', np.arcsin(a))	
print('对矩阵a中每个元素取反余弦: ',np.arccos(a))
print('对矩阵a中每个元素取反正切: ',np.arctan(a))
print('对矩阵a中每个元素取指数函数: ',np.exp(a))
print('对矩阵a中每个元素开根号: ',np.sqrt(a))

最大值所在位置的索引： 3
每一行最大值所在位置的索引： [0 0]
每一行最小值所在位置的索引： [1 1]
索引为1的最小，索引为0的最大: 
 [[1 2 0]
 [1 2 0]]
对矩阵a中每个元素取正弦:  [[-0.99999021  0.84147098  0.90929743]
 [-0.53657292  0.98935825  0.41211849]]
对矩阵a中每个元素取余弦:  [[ 0.0044257   0.54030231 -0.41614684]
 [ 0.84385396 -0.14550003 -0.91113026]]
对矩阵a中每个元素取正切:  [[-225.95084645    1.55740772   -2.18503986]
 [  -0.63585993   -6.79971146   -0.45231566]]
对矩阵a中每个元素取反正弦:  [[       nan 1.57079633        nan]
 [       nan        nan        nan]]
对矩阵a中每个元素取反余弦:  [[nan  0. nan]
 [nan nan nan]]
对矩阵a中每个元素取反正切:  [[1.48013644 0.78539816 1.10714872]
 [1.48765509 1.44644133 1.46013911]]
对矩阵a中每个元素取指数函数:  [[5.98741417e+04 2.71828183e+00 7.38905610e+00]
 [1.62754791e+05 2.98095799e+03 8.10308393e+03]]
对矩阵a中每个元素开根号:  [[3.31662479 1.         1.41421356]
 [3.46410162 2.82842712 3.        ]]


In [23]:
a = np.arange(9, dtype = np.float_).reshape(3,3)
b = np.array([10,10,10])
print('%s+\n%s=\n%s：'% (a,b, np.add(a,b)))
print('两个数组相减：\n', np.subtract(a,b))
print('两个数组相乘：\n', np.multiply(a,b))
print('两个数组相除：\n', np.divide(a,b))
print('power运算：\n', np.power(a,2))

a = np.array([10,20,30]) 
b = np.array([3,5,7])  
print('求余数：',np.mod(a,b),np.remainder(a,b))


[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]+
[10 10 10]=
[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]：
两个数组相减：
 [[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]
两个数组相乘：
 [[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]
两个数组相除：
 [[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]
power运算：
 [[ 0.  1.  4.]
 [ 9. 16. 25.]
 [36. 49. 64.]]
求余数： [1 0 2] [1 0 2]


In [24]:
# reciprocal求倒数
a = np.array([-1,0, 0.25,  1, 1.33, 100])  
b = np.array([-1,1,2,10,100], dtype =  int)  

print('求倒数:',np.reciprocal(a))
print('绝对值大于1的整型的倒数均为0：',np.reciprocal(b))


求倒数: [-1.               inf  4.         1.         0.7518797  0.01     ]
绝对值大于1的整型的倒数均为0： [-1  1  0  0  0]


In [25]:
# 复数
a = np.array([-5.6j,  0.2j,  11.  ,  1+1j])  
print('我们的数组是：',a)
print('实部： ', np.real(a))
print('虚部： ', np.imag(a))
print('共轭复数: ',np.conj(a))
print('返回弧度： ',np.angle(a))
print('返回角度： ',np.angle(a, deg =  True))

我们的数组是： [-0.-5.6j  0.+0.2j 11.+0.j   1.+1.j ]
实部：  [-0.  0. 11.  1.]
虚部：  [-5.6  0.2  0.   1. ]
共轭复数:  [-0.+5.6j  0.-0.2j 11.-0.j   1.-1.j ]
返回弧度：  [-1.57079633  1.57079633  0.          0.78539816]
返回角度：  [-90.  90.   0.  45.]


In [26]:
#排序与搜索
a = np.array([[13,7],[9,10]])  
print('原始矩阵： \n',a)
print('行内排序： \n',np.sort(a))
print('对行排序： \n',np.sort(a, axis =  0))

dt = np.dtype([('name',  'S10'),('age',  int)]) 
b = np.array([("raju",21),("anil",25),("ravi",  17),  ("amar",27)], dtype = dt)  
print('按name字段排序：',np.sort(b, order =  'name'))

print('返回索引: \n',np.argsort(a))

c =  ('b3','a2','b4','a1') 
d =  ('a',  'b',  'b',  'a') 
ind = np.lexsort((d,c))
print('lexsort的最后一个参数c是排序主键，其次是d：',ind)

print([c[i]  +  "+"  + d[i]  for i in ind])

原始矩阵： 
 [[13  7]
 [ 9 10]]
行内排序： 
 [[ 7 13]
 [ 9 10]]
对行排序： 
 [[ 9  7]
 [13 10]]
按name字段排序： [(b'amar', 27) (b'anil', 25) (b'raju', 21) (b'ravi', 17)]
返回索引: 
 [[1 0]
 [0 1]]
lexsort的最后一个参数c是排序主键，其次是d： [3 1 0 2]
['a1+a', 'a2+b', 'b3+a', 'b4+b']


In [27]:
# 查询
x = np.arange(9.).reshape(3,3)
y = np.where(x > 3)
print(x,y,x[y])

# 提取
print(np.extract(np.mod(x,2)==0, x))


[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]] (array([1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2])) [4. 5. 6. 7. 8.]
[0. 2. 4. 6. 8.]


In [28]:
# 字节交换
a = np.array([1,  256,  8755], dtype = np.int16)  
print(a,list(map(hex,a)))
print(a.byteswap(True), list(map(hex,a)))


[   1  256 8755] ['0x1', '0x100', '0x2233']
[  256     1 13090] ['0x100', '0x1', '0x3322']


In [29]:
# copy
a = np.arange(12)
b = a
print(id(a),id(b))

# 浅copy
c = a.view()
d=c.reshape(3,4)
print(id(a),id(c),id(d))
print('修改view的shape不影响原矩阵：',a,d,sep='\n---\n')

d[1,1]=100
print('修改view中的数据原矩阵也会变：',a,d,sep='\n---\n')

# 深copy
e = a.copy()

print('切片也是view,view没有自己的数据：',
                [i.flags.owndata for i in [a,b,c,d,e,a[:3]]],
                [i.base is a     for i in [a,b,c,d,e,a[:3]]],sep='\n---\n')


140484225759552 140484225759552
140484225759552 140484225759952 140484225760032
修改view的shape不影响原矩阵：
---
[ 0  1  2  3  4  5  6  7  8  9 10 11]
---
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
修改view中的数据原矩阵也会变：
---
[  0   1   2   3   4 100   6   7   8   9  10  11]
---
[[  0   1   2   3]
 [  4 100   6   7]
 [  8   9  10  11]]
切片也是view,view没有自己的数据：
---
[True, True, False, False, True, False]
---
[False, False, True, True, False, True]
