# 线性代数


<br>




In [2]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
c=np.array([1,2,3,4])
d=np.array([11,12,13,14])
print('一维数组的向量内积:',np.inner(c,d),np.dot(c,d),np.matmul(c,d))
print('二维数组的向量内积:',np.vdot(a,b))

# 外积
print('[[1*11+2*13, 1*12+2*14]\n[3*11+4*13, 3*12+4*14]]\n---\n',np.dot(a,b),np.matmul(a,b),sep='\n---\n')

e=[1,2]
print('如果任一参数是一维数组，则通过在其维度上附加1来将其提升为矩阵，并在乘法之后被去除:')
print('%s*%s=%s'%(a,e,np.matmul(a,e)))
print('%s*%s=%s'%(e,a,np.matmul(e,a)))

print('等价于：',np.dot(a,e),np.dot(e,a))



一维数组的向量内积: 130 130 130
二维数组的向量内积: 130
[[1*11+2*13, 1*12+2*14]
[3*11+4*13, 3*12+4*14]]
---

---
[[37 40]
 [85 92]]
---
[[37 40]
 [85 92]]
如果任一参数是一维数组，则通过在其维度上附加1来将其提升为矩阵，并在乘法之后被去除:
[[1 2]
 [3 4]]*[1, 2]=[ 5 11]
[1, 2]*[[1 2]
 [3 4]]=[ 7 10]
等价于： [ 5 11] [ 7 10]


In [3]:
#有的矩阵没有逆矩阵
A = np.array([[0, 1,2],
              [1, 0,3],
              [4,-3,8]])
B=np.linalg.inv(A)     #B是A的逆矩阵，AB=BA=E
# A.dot(B)=np.dot(A,B)=A@B (叉乘 or 点积：各元素相乘后相加, 要求第一个矩阵的列数等于第二个矩阵的行数)
# A*B=np.multiply(A,B) (点乘：各对应位置元素相乘，要求两个矩阵大小相同)
print('ndarray乘法： ',A,B,A*B,A.dot(B),A@B,sep='\n---\n')
print('转置矩阵： \n',A.T)

A = np.eye(3)           # 3阶单位矩阵
print(np.linalg.inv(A)) # 单位矩阵的逆为他本身
print("转化成matrix的2种方法：",np.asmatrix(A), np.mat(A),sep='\n---\n')

ndarray乘法： 
---
[[ 0  1  2]
 [ 1  0  3]
 [ 4 -3  8]]
---
[[-4.5  7.  -1.5]
 [-2.   4.  -1. ]
 [ 1.5 -2.   0.5]]
---
[[-0.  7. -3.]
 [-2.  0. -3.]
 [ 6.  6.  4.]]
---
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
---
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
转置矩阵： 
 [[ 0  1  4]
 [ 1  0 -3]
 [ 2  3  8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
转化成matrix的2种方法：
---
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
---
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
#matrix: 
A = np.mat("0 1 2;1 0 3;4 -3 8")
B = np.linalg.inv(A)
# A*B=np.dot(A,B)=A.dot(B)  (都表示叉乘，各元素相乘后相加)
# np=np.multiply(A,B)       (点乘要用multiply函数)
print ('matrix乘法： ',A,B,A * B, A.dot(B),np.multiply(A,B),sep='\n---\n')
print('转置矩阵： \n',A.T)  # 行和列互相交换
print('共轭矩阵： \n',A.H)
print('逆矩阵： \n',A.I)
print("转化成ndarray： \n",np.asarray(A))

# 使用pinv函数计算广义逆矩阵
print ('inv函数只接受方阵作为输入矩阵，而pinv函数则没有这个限制: \n',np.linalg.pinv(A))



matrix乘法： 
---
[[ 0  1  2]
 [ 1  0  3]
 [ 4 -3  8]]
---
[[-4.5  7.  -1.5]
 [-2.   4.  -1. ]
 [ 1.5 -2.   0.5]]
---
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
---
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
---
[[-0.  7. -3.]
 [-2.  0. -3.]
 [ 6.  6.  4.]]
转置矩阵： 
 [[ 0  1  4]
 [ 1  0 -3]
 [ 2  3  8]]
共轭矩阵： 
 [[ 0  1  4]
 [ 1  0 -3]
 [ 2  3  8]]
逆矩阵： 
 [[-4.5  7.  -1.5]
 [-2.   4.  -1. ]
 [ 1.5 -2.   0.5]]
转化成ndarray： 
 [[ 0  1  2]
 [ 1  0  3]
 [ 4 -3  8]]
inv函数只接受方阵作为输入矩阵，而pinv函数则没有这个限制:  [[-4.5  7.  -1.5]
 [-2.   4.  -1. ]
 [ 1.5 -2.   0.5]]


In [5]:
# 求解线性方程组
# 创建矩阵和数组
A = np.mat("1 -2 1;0 2 -8;-4 5 9") 
b = np.array([0,8,-9])

# 调用solve函数求解线性方程组Ax = b, 其中 A 为矩阵，b 为一维或二维的数组，x 是未知变量
x=np.linalg.solve(A,b)
print ('%s * %s = %s'% (A,x,np.dot(A, x)))


[[ 1 -2  1]
 [ 0  2 -8]
 [-4  5  9]] * [29. 16.  3.] = [[ 0.  8. -9.]]


In [6]:
b = np.array([[6,1,1], [4, -2, 5], [2,8,7]]) 
print('6*(-2*7 - 5*8) - 1*(4*7 - 5*2) + 1*(4*8 - -2*2)=', np.linalg.det(b))


6*(-2*7 - 5*8) - 1*(4*7 - 5*2) + 1*(4*8 - -2*2)= -306.0


In [7]:
# 特征值和特征向量
# A 是一个n阶方阵，如果存在标量a满足方程 Ax = ax，则a为A的特征值，x为A属于a的特征向量
A = np.mat("3 -2;1 0")
print ('特征值',np.linalg.eigvals(A))
print('特征值和特征向量:\n', np.linalg.eig(A))

a,x=np.linalg.eig(A)
# 使用dot函数验证求得的解是否正确
for i in range(len(a)):
    print('---\na=%s \n x=%s \n x[:,i]=%s \n' % (a[i],x[i],x[:,i]))
    print ("Ax:",np.dot(A,x[:,i]))
    print ("ax:",a[i] * x[:,i])


特征值 [2. 1.]
特征值和特征向量:
 (array([2., 1.]), matrix([[0.89442719, 0.70710678],
        [0.4472136 , 0.70710678]]))
---
a=2.0 
 x=[[0.89442719 0.70710678]] 
 x[:,i]=[[0.89442719]
 [0.4472136 ]] 

Ax: [[1.78885438]
 [0.89442719]]
ax: [[1.78885438]
 [0.89442719]]
---
a=1.0 
 x=[[0.4472136  0.70710678]] 
 x[:,i]=[[0.70710678]
 [0.70710678]] 

Ax: [[0.70710678]
 [0.70710678]]
ax: [[0.70710678]
 [0.70710678]]


In [8]:
# 奇异值分解（SVD，Singular Value Decomposition）
# SVD是一种因子分解运算，将一个矩阵分解为3个矩阵的乘积
# svd函数返回3个矩阵——U、Sigma和V，其中U和V是正交矩阵，Sigma包含输入矩阵的奇异值。

A = np.mat("4 11 14;8 7 -2")
# 使用svd函数分解矩阵
U,Sigma,V = np.linalg.svd(A,full_matrices=False)
print("U=%s \nV=%s:" % (U,V))
print ("diag函数生成完整的奇异值矩阵, Sigma=%s\n---\n" % Sigma, np.diag(Sigma))

# 使用diag函数生成完整的奇异值矩阵。将分解出的3个矩阵相乘
print ('验证：\n', U * np.diag(Sigma) * V)


U=[[-0.9486833  -0.31622777]
 [-0.31622777  0.9486833 ]] 
V=[[-0.33333333 -0.66666667 -0.66666667]
 [ 0.66666667  0.33333333 -0.66666667]]:
diag函数生成完整的奇异值矩阵, Sigma=[18.97366596  9.48683298]
---
 [[18.97366596  0.        ]
 [ 0.          9.48683298]]
验证：
 [[ 4. 11. 14.]
 [ 8.  7. -2.]]


In [9]:
# 行列式 detA=|A|,是一个数值 
# https://blog.csdn.net/DrIcetar/article/details/81297446

A = np.mat("3 4;5 6")
print('3*6-4*5=',np.linalg.det(A))


3*6-4*5= -1.9999999999999971
