## PCA 算法模拟

In [3]:
A = np.array([[3, 2000], 
              [2, 3000], 
              [4, 5000], 
              [5, 8000], 
              [1, 2000]], dtype='float')

# 数据归一化
mean = np.mean(A, axis=0)
norm = A - mean
# 数据缩放
scope = np.max(norm, axis=0) - np.min(norm, axis=0)
norm = norm / scope
norm

[[ 0.         -0.33333333]
 [-0.25       -0.16666667]
 [ 0.25        0.16666667]
 [ 0.5         0.66666667]
 [-0.5        -0.33333333]]

In [4]:
U, S, V = np.linalg.svd(np.dot(norm.T, norm))
U

[[-0.67710949 -0.73588229]
 [-0.73588229  0.67710949]]

In [5]:
U_reduce = U[:, 0].reshape(2,1)
U_reduce

[[-0.67710949]
 [-0.73588229]]

In [6]:
R = np.dot(norm, U_reduce)
R

[[ 0.2452941 ]
 [ 0.29192442]
 [-0.29192442]
 [-0.82914294]
 [ 0.58384884]]

In [7]:
Z = np.dot(R, U_reduce.T)
Z

[[-0.16609096 -0.18050758]
 [-0.19766479 -0.21482201]
 [ 0.19766479  0.21482201]
 [ 0.56142055  0.6101516 ]
 [-0.39532959 -0.42964402]]

In [8]:
np.multiply(Z, scope) + mean

[[2.33563616e+00 2.91695452e+03]
 [2.20934082e+00 2.71106794e+03]
 [3.79065918e+00 5.28893206e+03]
 [5.24568220e+00 7.66090960e+03]
 [1.41868164e+00 1.42213588e+03]]

## 使用 sklearn 包实现

In [10]:
from sklearn.decomposition import PCA
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler

def std_PCA(**argv):
    scaler = MinMaxScaler()
    pca = PCA(**argv)
    pipeline = Pipeline([('scaler', scaler),
                         ('pca', pca)])
    return pipeline

pca = std_PCA(n_components=1)
R2 = pca.fit_transform(A)
R2

[[-0.2452941 ]
 [-0.29192442]
 [ 0.29192442]
 [ 0.82914294]
 [-0.58384884]]

In [11]:
pca.inverse_transform(R2)

[[2.33563616e+00 2.91695452e+03]
 [2.20934082e+00 2.71106794e+03]
 [3.79065918e+00 5.28893206e+03]
 [5.24568220e+00 7.66090960e+03]
 [1.41868164e+00 1.42213588e+03]]

## 降维及恢复示意图

In [13]:
plt.figure(figsize=(8, 8), dpi=144)

plt.title('Physcial meanings of PCA')

ymin = xmin = -1
ymax = xmax = 1
plt.xlim(xmin, xmax)
plt.ylim(ymin, ymax)
ax = plt.gca()                                  # gca 代表当前坐标轴，即 'get current axis'
ax.spines['right'].set_color('none')            # 隐藏坐标轴
ax.spines['top'].set_color('none')

plt.scatter(norm[:, 0], norm[:, 1], marker='s', c='b')
plt.scatter(Z[:, 0], Z[:, 1], marker='o', c='r')
plt.arrow(0, 0, U[0][0], U[1][0], color='r', linestyle='-')
plt.arrow(0, 0, U[0][1], U[1][1], color='r', linestyle='--')
plt.annotate(r'$U_{reduce} = u^{(1)}$',
             xy=(U[0][0], U[1][0]), xycoords='data',
             xytext=(U_reduce[0][0] + 0.2, U_reduce[1][0] - 0.1), fontsize=10,
             arrowprops=dict(arrowstyle="->", connectionstyle="arc3,rad=.2"))
plt.annotate(r'$u^{(2)}$',
             xy=(U[0][1], U[1][1]), xycoords='data',
             xytext=(U[0][1] + 0.2, U[1][1] - 0.1), fontsize=10,
             arrowprops=dict(arrowstyle="->", connectionstyle="arc3,rad=.2"))
plt.annotate(r'raw data',
             xy=(norm[0][0], norm[0][1]), xycoords='data',
             xytext=(norm[0][0] + 0.2, norm[0][1] - 0.2), fontsize=10,
             arrowprops=dict(arrowstyle="->", connectionstyle="arc3,rad=.2"))
plt.annotate(r'projected data',
             xy=(Z[0][0], Z[0][1]), xycoords='data',
             xytext=(Z[0][0] + 0.2, Z[0][1] - 0.1), fontsize=10,
             arrowprops=dict(arrowstyle="->", connectionstyle="arc3,rad=.2"))
plt.show()             

<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
 "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Created with matplotlib (https://matplotlib.org/) -->
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 <!-- −1.00 -->
 
 
 
 
 <path d="M 31.78125 66.40625 
Q 24.171875 66.40625 20.328125 58.90625 
Q 16.5 51.421875 16.5 36.375 
Q 16.5 21.390625 20.328125 13.890625 
Q 24.171875 6.390625 31.78125 6.390625 
Q 39.453125 6.390625 43.28125 13.890625 
Q 47.125 21.390625 47.125 36.375 
Q 47.125 51.421875 43.28125 58.90625 
Q 39.453125 66.40625 31.78125 66.40625 
z
M 31.78125 74.21875 
Q 44.046875 74.21875 50.515625 64.515625 
Q 56.984375 54.828125 56.984375 36.375 
Q 56.984375 17.96875 50.515625 8.265625 
Q 44.046875 -1.421875 31.78125 -1.421875 
Q 19.53125 -1.421875 13.0625 8.265625 
Q 6.59375 17.96875 6.59375 36.375 
Q 6.59375 54.828125 13.0625 64.515625 
Q 19.53125 74.21875 31.78125 74.21875 
z
" id="DejaVuSans-48"/>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 <!-- −0.75 -->
 
 
 <path d="M 10.796875 72.90625 
L 49.515625 72.90625 
L 49.515625 64.59375 
L 19.828125 64.59375 
L 19.828125 46.734375 
Q 21.96875 47.46875 24.109375 47.828125 
Q 26.265625 48.1875 28.421875 48.1875 
Q 40.625 48.1875 47.75 41.5 
Q 54.890625 34.8125 54.890625 23.390625 
Q 54.890625 11.625 47.5625 5.09375 
Q 40.234375 -1.421875 26.90625 -1.421875 
Q 22.3125 -1.421875 17.546875 -0.640625 
Q 12.796875 0.140625 7.71875 1.703125 
L 7.71875 11.625 
Q 12.109375 9.234375 16.796875 8.0625 
Q 21.484375 6.890625 26.703125 6.890625 
Q 35.15625 6.890625 40.078125 11.328125 
Q 45.015625 15.765625 45.015625 23.390625 
Q 45.015625 31 40.078125 35.4375 
Q 35.15625 39.890625 26.703125 39.890625 
Q 22.75 39.890625 18.8125 39.015625 
Q 14.890625 38.140625 10.796875 36.28125 
z
" id="DejaVuSans-53"/>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 <!-- −0.50 -->
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 <!-- −0.25 -->
 
 <path d="M 19.1875 8.296875 
L 53.609375 8.296875 
L 53.609375 0 
L 7.328125 0 
L 7.328125 8.296875 
Q 12.9375 14.109375 22.625 23.890625 
Q 32.328125 33.6875 34.8125 36.53125 
Q 39.546875 41.84375 41.421875 45.53125 
Q 43.3125 49.21875 43.3125 52.78125 
Q 43.3125 58.59375 39.234375 62.25 
Q 35.15625 65.921875 28.609375 65.921875 
Q 23.96875 65.921875 18.8125 64.3125 
Q 13.671875 62.703125 7.8125 59.421875 
L 7.8125 69.390625 
Q 13.765625 71.78125 18.9375 73 
Q 24.125 74.21875 28.421875 74.21875 
Q 39.75 74.21875 46.484375 68.546875 
Q 53.21875 62.890625 53.21875 53.421875 
Q 53.21875 48.921875 51.53125 44.890625 
Q 49.859375 40.875 45.40625 35.40625 
Q 44.1875 33.984375 37.640625 27.21875 
Q 31.109375 20.453125 19.1875 8.296875 
z
" id="DejaVuSans-50"/>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 <!-- 0.00 -->
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 <!-- 0.25 -->
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 <!-- 0.50 -->
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 <!-- 0.75 -->
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 <!-- 1.00 -->
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 <!-- −1.00 -->
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 <!-- −0.75 -->
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 <!-- −0.50 -->
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 <!-- −0.25 -->
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 <!-- 0.00 -->
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 <!-- 0.25 -->
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 <!-- 0.50 -->
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 <!-- 0.75 -->
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 <!-- 1.00 -->
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 <!-- $U_{reduce} = u^{(1)}$ -->
 
 <path d="M 15.484375 72.90625 
L 25.390625 72.90625 
L 16.796875 28.609375 
Q 16.265625 25.640625 16.046875 23.703125 
Q 15.828125 21.78125 15.828125 20.3125 
Q 15.828125 13.578125 19.578125 10.078125 
Q 23.34375 6.59375 30.609375 6.59375 
Q 40.046875 6.59375 45.28125 11.765625 
Q 50.53125 16.9375 52.78125 28.609375 
L 61.375 72.90625 
L 71.296875 72.90625 
L 62.5 27.390625 
Q 59.625 12.64062