# 线性回归


This is a text cell. Start editing!




In [1]:
class linear_regression_gradient_descent:
    def __init__(self,x,y,eps,alpha,max_iter_times):
        '''
        initalize feature、dependent variable 、learning rate、iteration times
        :param x:
        :param y:
        :param alpha:
        :param max_iter_times:
        '''
        self.x=x
        self.y=y
        self.n = len(self.x)
        self.w=np.zeros((x.shape[1],1))
        self.alpha=alpha
        self.iteration=max_iter_times
        self.eps=eps
        self.cost_review=np.zeros((0,0))

    def error_function(self):
        '''
        compute error of training data in every iteration
        :return:a vector of error
        '''
        # step1 compute cost function
        n = len(self.x)
        y_pred = np.dot(self.x, self.w)
        error = y_pred - self.y
        return error

    def partial_devative(self):
        '''
        compute the partial derivatives of cost functions on theta in every turn
        :return:
        '''
        n = len(self.x)
        error = self.error_function()
        delta_w = np.dot(self.x.T, error) / n
        return delta_w

    def batch_gradient_descent(self):
        '''
        gradient descent to solve the parameter of linear regression
        :return:
        '''
        n = len(self.x)
        itera = 0
        error = self.error_function()
        cost = np.sum(error ** 2) / 2 * n
        print(error,cost)
        while (itera < self.iteration or cost > self.eps):
            #step1 compute the partial derivatives of cost functions on theta
            delta_w = self.partial_devative()
            #step2 update theta
            self.w = self.w - self.alpha * delta_w
            #step3 compute cost function
            error = self.error_function()
            cost = np.sum(error ** 2) / 2 * n
           # print cost
            self.cost_review=np.append(self.cost_review, cost)
            itera += 1
            print(error,cost)
        return self.w

In [2]:
x = np.array([[1, 2, 2, 0, 1], [3, 4, 2, 0, 1], [2, 5, 1, 0, 2], [2, 3, 5, 1, 3], [1, 4, 2, 3, 1], [3, 4, 2, 2, 1]])
x_theta0 = np.ones(x.shape[0])
# insert a full-1 col in the first col of X matrix to get the design matrix
design_matrix = np.insert(x, 0, values=x_theta0, axis=1)
y = np.array([1.2, 0.4, 0.6, 2.1, 0.9, 0.3]).reshape((len(design_matrix), 1))
lr = linear_regression_gradient_descent(design_matrix,y,0.15,0.01,100)
w=lr.batch_gradient_descent()
print("parameter of linear regression:"+str(w))
print("iteration times are:"+str(len(lr.cost_review)))


[[-1.2]
 [-0.4]
 [-0.6]
 [-2.1]
 [-0.9]
 [-0.3]] 21.81
[[-1.04166667]
 [-0.14933333]
 [-0.34583333]
 [-1.76866667]
 [-0.65433333]
 [-0.03133333]] 14.35285875
[[-0.9264425 ]
 [ 0.02897583]
 [-0.16598528]
 [-1.52461583]
 [-0.47860917]
 [ 0.15962361]] 10.39705886416435
[[-0.84223065]
 [ 0.15531153]
 [-0.03948867]
 [-1.34342265]
 [-0.35313567]
 [ 0.2947633 ]] 8.254224338240169
[[-0.7803358 ]
 [ 0.24432431]
 [ 0.04872544]
 [-1.20752896]
 [-0.26375959]
 [ 0.38982042]] 7.0519432859382105
[[-0.73450758]
 [ 0.30654373]
 [ 0.10948667]
 [-1.10431213]
 [-0.20030857]
 [ 0.45610372]] 6.339351589467408
[[-0.70025292]
 [ 0.34953735]
 [ 0.15057756]
 [-1.02469711]
 [-0.15547155]
 [ 0.50174078]] 5.8833704686764605
[[-0.67434184]
 [ 0.3787438 ]
 [ 0.17759057]
 [-0.96215869]
 [-0.12399404]
 [ 0.53257266]] 5.5634390952476505
[[-0.65445227]
 [ 0.3980715 ]
 [ 0.19454405]
 [-0.91200447]
 [-0.10209977]
 [ 0.55279702]] 5.317131421403718
[[-0.63891468]
 [ 0.41032906]
 [ 0.20432498]
 [-0.87085945]
 [-0.08707489]
 

In [3]:
#show the curve of cost function
fig=plt.figure(1)
plt.plot(lr.cost_review,color='r')
plt.ylim(ymin=np.min(lr.cost_review),ymax=np.max(lr.cost_review))
plt.xlim(xmin=0,xmax=len(lr.cost_review)+1)
plt.ylabel("cost function")
plt.xlabel("id of iteration")
plt.title("cost function of linear regression")
plt.grid()
plt.show()

<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
 "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Created with matplotlib (https://matplotlib.org/) -->
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 <!-- 0 -->
 
 <path d="M 50.390625 35.796875 
Q 50.390625 27.15625 49.140625 20.3125 
Q 47.90625 13.484375 45.140625 8.734375 
Q 42.390625 4 38.03125 1.5 
Q 33.6875 -0.984375 27.484375 -0.984375 
Q 21.734375 -0.984375 17.453125 1.5 
Q 13.1875 4 10.375 8.734375 
Q 7.5625 13.484375 6.171875 20.3125 
Q 4.78125 27.15625 4.78125 35.796875 
Q 4.78125 44.4375 6.03125 51.265625 
Q 7.28125 58.109375 9.984375 62.8125 
Q 12.703125 67.53125 17.015625 70.015625 
Q 21.34375 72.515625 27.484375 72.515625 
Q 33.296875 72.515625 37.59375 70.046875 
Q 41.890625 67.578125 44.71875 62.859375 
Q 47.5625 58.15625 48.96875 51.3125 
Q 50.390625 44.484375 50.390625 35.796875 
z
M 13.8125 35.796875 
Q 13.8125 28.46875 14.546875 23 
Q 15.28125 17.53125 16.890625 13.890625 
Q 18.5 10.25 21.109375 8.421875 
Q 23.734375 6.59375 27.484375 6.59375 
Q 31.25 6.59375 33.890625 8.390625 
Q 36.53125 10.203125 38.203125 13.8125 
Q 39.890625 17.4375 40.640625 22.921875 
Q 41.40625 28.421875 41.40625 35.796875 
Q 41.40625 43.109375 40.640625 48.578125 
Q 39.890625 54.046875 38.203125 57.65625 
Q 36.53125 61.28125 33.890625 63.078125 
Q 31.25 64.890625 27.484375 64.890625 
Q 23.734375 64.890625 21.109375 63.078125 
Q 18.5 61.28125 16.890625 57.65625 
Q 15.28125 54.046875 14.546875 48.578125 
Q 13.8125 43.109375 13.8125 35.796875 
z
" id="WenQuanYiMicroHei-48"/>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 <!-- 200 -->
 
 <path d="M 49.21875 0 
L 4.6875 0 
L 4.6875 7.625 
L 21.78125 26.21875 
Q 25.4375 30.171875 28.3125 33.4375 
Q 31.203125 36.71875 33.21875 39.84375 
Q 35.25 42.96875 36.328125 46.109375 
Q 37.40625 49.265625 37.40625 52.984375 
Q 37.40625 55.859375 36.578125 58.046875 
Q 35.75 60.25 34.203125 61.78125 
Q 32.671875 63.328125 30.5625 64.109375 
Q 28.46875 64.890625 25.875 64.890625 
Q 21.234375 64.890625 17.5 63.015625 
Q 13.765625 61.140625 10.40625 58.203125 
L 5.421875 64.015625 
Q 7.375 65.765625 9.609375 67.296875 
Q 11.859375 68.84375 14.453125 69.96875 
Q 17.046875 71.09375 19.921875 71.75 
Q 22.796875 72.40625 25.984375 72.40625 
Q 30.671875 72.40625 34.453125 71.09375 
Q 38.234375 69.78125 40.859375 67.3125 
Q 43.5 64.84375 44.9375 61.296875 
Q 46.390625 57.765625 46.390625 53.328125 
Q 46.390625 49.171875 45.09375 45.40625 
Q 43.796875 41.65625 41.53125 38.015625 
Q 39.265625 34.375 36.109375 30.703125 
Q 32.953125 27.046875 29.296875 23.09375 
L 15.578125 8.5 
L 15.578125 8.109375 
L 49.21875 8.109375 
z
" id="WenQuanYiMicroHei-50"/>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 <!-- 400 -->
 
 <path d="M 53.078125 16.015625 
L 42.671875 16.015625 
L 42.671875 0 
L 34.078125 0 
L 34.078125 16.015625 
L 1.125 16.015625 
L 1.125 23.78125 
L 33.5 71.78125 
L 42.671875 71.78125 
L 42.671875 24.125 
L 53.078125 24.125 
z
M 34.078125 24.125 
L 34.078125 41.5 
Q 34.078125 44.234375 34.15625 47.234375 
Q 34.234375 50.25 34.328125 53.09375 
Q 34.421875 55.953125 34.546875 58.4375 
Q 34.671875 60.9375 34.71875 62.59375 
L 34.28125 62.59375 
Q 33.9375 61.625 33.421875 60.421875 
Q 32.90625 59.234375 32.296875 58.03125 
Q 31.6875 56.84375 31.046875 55.71875 
Q 30.421875 54.59375 29.890625 53.8125 
L 9.8125 24.125 
z
" id="WenQuanYiMicroHei-52"/>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 <!-- 600 -->
 
 <path d="M 5.515625 30.515625 
Q 5.515625 35.640625 6.03125 40.71875 
Q 6.546875 45.796875 7.828125 50.453125 
Q 9.125 55.125 11.375 59.125 
Q 13.625 63.140625 17.09375 66.09375 
Q 20.5625 69.046875 25.390625 70.71875 
Q 30.21875 72.40625 36.71875 72.40625 
Q 37.640625 72.40625 38.765625 72.359375 
Q 39.890625 72.3125 41.03125 72.1875 
Q 42.1875 72.078125 43.234375 71.90625 
Q 44.28125 71.734375 45.125 71.484375 
L 45.125 63.921875 
Q 43.40625 64.5 41.25 64.796875 
Q 39.109375 65.09375 37.015625 65.09375 
Q 32.625 65.0